PricingPortalExample/PricingPortalExample/Models/Spa.cs
using System.ComponentModel.DataAnnotations;

namespace PricingPortalExample.Models
{
    public class Spa
    {
        public int ID { get; set; }

        [Required]
        public string Agreement { get; set; }

        [Required]
        public int Country { get; set; }

        [Required]
        [StringLength(15)]
        public string ProjectDescription { get; set; }
    }
}

PricingPortalExample/PricingPortalExample/Models/ViewModels/SpaViewModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace PricingPortalExample.Models.ViewModels
{
    public class SpaViewModel
    {
        public Spa Spa { get; set; }

        public IEnumerable<SelectListItem> Countries { get; }

        public SpaViewModel()
        {
            Spa = new Spa();

            Countries = new List<SelectListItem>
            {
                new SelectListItem {Text = "Choose an option", Value = string.Empty},
                new SelectListItem {Text = "United Kingdom", Value = "0"},
                new SelectListItem {Text = "Austria", Value = "1"},
                new SelectListItem {Text = "Netherlands", Value = "2"}
            };
        }
    }
}

PricingPortalExample/PricingPortalExample/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PricingPortalExample.Data;

namespace PricingPortalExample.Controllers
{
    public class HomeController : Controller
    {
        private ISpaRepository repository;

        public HomeController(ISpaRepository repository)
        {
            this.repository = repository;
        }

        public ViewResult Index()
        {
            return View();
        }
    }
}

PricingPortalExample/PricingPortalExample/Controllers/SpaController.cs
using Microsoft.AspNetCore.Mvc;
using PricingPortalExample.Data;
using PricingPortalExample.Models;
using PricingPortalExample.Models.ViewModels;

namespace PricingPortalExample.Controllers
{
    public class SpaController : Controller
    {
        private ISpaRepository repository;

        public SpaController(ISpaRepository repository)
        {
            this.repository = repository;
        }

        public ViewResult Create()
        {
            return View(new SpaViewModel());
        }

        [HttpPost]
        public ActionResult Create(SpaViewModel spa)
        {
            if (ModelState.IsValid)
            {
                // code to save for real repo goes here...
                return RedirectToAction("Index", "Home");
            }

            return View(spa);
        }

        //[HttpPost]
        //public ActionResult Create(Spa spa)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        // code to save for real repo goes here...
        //        return RedirectToAction("Index", "Home");
        //    }

        //    return View();
        //}
    }
}

PricingPortalExample/PricingPortalExample/Views/Home/Index.cshtml
@model IEnumerable<Spa>

<h1 class="main-title my-4">Dashboard</h1>

<div class="row">
    <a class="btn btn-primary" asp-controller="Spa" asp-action="Create" role="button">New request</a>
</div>

PricingPortalExample/PricingPortalExample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>PricingPortal</title>
    <environment names="Development">
        <link href="~/css/bootstrap.css" rel="stylesheet" />
        <link href="~/css/site.css" rel="stylesheet" />
    </environment>
</head>
<body>
<div class="navbar fixed-top navbar-dark bg-dark">
    <div class="container">
        <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Pricing Portal</a>
    </div>
</div>
<div class="container">
    @RenderBody()
</div>
<environment names="Development">
    <script src="~/js/jquery-3.3.1.js"></script>
    <script src="~/js/bootstrap.js"></script>
</environment>
</body>
</html>

PricingPortalExample/PricingPortalExample/Views/Spa/Create.cshtml
@model SpaViewModel

<h1 class="main-title my-4">New SPA Request</h1>

<form asp-action="Create" method="post">

    <div class="row">
        <div class="col-md-6">
            <div class="form-group row">
                <label asp-for="Spa.Agreement" class="col-sm-4 col-form-label col-form-label-sm">Agreement</label>
                <div class="col-sm-8">
                    <input class="form-control form-control-sm" asp-for="Spa.Agreement"/>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Spa.Country" class="col-sm-4 col-form-label col-form-label-sm">Country</label>
                <div class="col-sm-8">
                    <select class="form-control form-control-sm" asp-for="Spa.Country" asp-items="Model.Countries"></select>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Spa.ProjectDescription" class="col-sm-4 col-form-label col-form-label-sm">Project description</label>
                <div class="col-sm-8">
                    <input class="form-control form-control-sm" asp-for="Spa.ProjectDescription"/>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group row">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </div>
    </div>

</form>